### PR TITLE
fix(connection): fix reflect

### LINKED ISSUE #60: Process comments from #59
Reflect was incorrectly introduced at some points in #59. It was merged anyway.

The comments from that PR should be fixed.

### PR DESCRIPTION
**Pull request by Lehren**
Fix reflect bugs that were unchecked.

Fix #60

### CODE REVIEW

File: administrative-sdk/connection.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ class Connection {
 
       const evs = self.events[name];
       evs.forEach(ev => {
-        Reflect.apply(ev, null, args);
+        ev(...args);
```
Comment (remcohaszing) [inline administrative-sdk/connection.js]: There are more occurrences

File: administrative-sdk/connection.js [hunk 2]
```diff
@@ -113,9 +113,9 @@ class Connection {
       console.log('WebSocket connection opened');
       self._session = session;
       const _call = self._session.call;
-      self._session.call = function(url) {
+      self._session.call = function(...url) {
         console.debug('Calling RPC: ' + url);
-        return Reflect.apply(_call, this, url);
+        return Reflect.apply(_call, this, ...url);
```
Comment (remcohaszing) [inline administrative-sdk/connection.js]: This changes the behaviour.

I think it should be something like this:

```js
self._session.call = function(url, ...args) {
  console.debug('Calling RPC: ' + url);
  return _call.call(this, url, ...args);
};
```

**Comment by Lehren** [comment]
Should be fixed in latest commit.
